services:
  literev-legal-deps:
    image: ghcr.io/thegraphnetwork-literev/literev-legal-deps:prod
    build:
      context: ..
      dockerfile: ./containers/Dockerfile
      args:
        ENV: prod
