name: literev-legal
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.10
  - compilers
  - nodejs >=18
  - yarn
  - poetry >=2
  - pip
  - pip:
      - compose-go
      - annoy==1.17.3 # not supporting PEP 517 builds
