name: literev-legal
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python 3.10
  - compilers
  - nodejs >=18
  - yarn
  - poetry >=2
  - libxcrypt
  - pip
  - pip:
      - compose-go<2.31.0
      - annoy==1.17.3
